### PR TITLE
Eu fa delete list

### LINKED ISSUE #11: 11. As a user, I want to be able to delete items from my shopping list so that my list isn’t cluttered with items I don’t want to buy in the future.
It’s possible our users may make an error when entering an item or may decide they won’t be buying a certain item again in the future. Let’s help them keep their lists tidy!

AC:

* User is able to delete an item from the shopping list
* Before deleting, prompt the user to confirm that they really want to delete the item to prevent accidental deletions
* Deletion should cause the associated record(s) in the database to be deleted

Notes:

* As noted in the wireframe https://github.com/the-collab-lab/smart-shopping-list/blob/main/_resources/wireframes/list-populated.png activating the "Delete" link should pop-up a confirmation dialog because this is a "destructive" action.
* Many teams jump to a modal as the solution here, but modals are fraught with accessibility concerns, so consider using a simple JavaScript confirm dialog.

### PR DESCRIPTION
**Pull request by fatima-ola**
## Description

This code allows users to delete an item from the shopping list so that their list isn’t cluttered with items they don’t want to buy in the future. The filter method approach was used because we have arrays of objects to loop through and check if an item is to be deleted or not. Yes we learnt how to use `filter()` method, `window.confirm()` method and how to delete a particular item from firestore database.

## Related Issue
closes #11 

## Acceptance Criteria

- The user is able to delete an item from the shopping list
- Before deleting, prompt the user to confirm that they really want to delete the item to prevent accidental deletions
- Deletion should cause the associated record(s) in the database to be deleted

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|  ✓ | :sparkles: New feature     |
|  ✓ | :hammer: Refactoring       |
|    | :100: Add tests            |
|    | :link: Update dependencies |
|    | :scroll: Docs              |

## Deleting oranges 
Screenshot from 2021-11-13 14-41-45

## Prompt to confirm delete
Screenshot from 2021-11-13 14-41-51

## Oranges was finally deleted from the user end and from the database
Screenshot from 2021-11-13 14-41-57

## Testing Steps / QA Criteria

- Pull the branch to your machine
- Run `npm install` to install all dependencies
- Run `npm start` to start the project on the browser `localhost:3000`
- If a list pops up, click on the delete button to delete, click yes to confirm and the item will be deleted. You can reload your page to confirm that it is deleted from the database as well. To be sure, after reloading the list of items appears without the deleted items.
- If you click cancel, the item will not be deleted.
- If you don't have any existing items, you can create a new item and add items to view all the lists on the list page
- Or join an existing list with one of the token here `vale lacy wrist` , `haydn lund lee` , `bunyan sri scour`

### CODE REVIEW

**Comment by adiati98** [comment]
Great job, team!
I can successfully delete an item, and it's deleted both on UI and database! 🎉

two thumbs up gif

**Comment by danachen** [comment]
Works well on my end!

Just one thing, does line 91 `else setItems(items);` do anything?

**Comment by fatima-ola** [comment]
> Works well on my end!
> 
> Just one thing, does line 91 `else setItems(items);` do anything?

I was trying to make sure all the items render if confirm is not true. But I just test again and it works perfectly well irrespective of the else 
Thank you for that. I will push the updated version

**Comment by fatima-ola** [comment]
> Works well on my end!
> 
> Just one thing, does line 91 `else setItems(items);` do anything?

I was trying to make sure all the items render if confirm is not true. But I just test again and it works perfectly well irrespective of the else 
Thank you for that. I will push the updated version

**Review by faysvas — COMMENTED** [review]
This looks good to me, great job!

**Pull request merged**
